# -*- mode: ruby -*-
# vi: set ft=ruby :

# plugins don't seem to be auto-loaded from the bundle
require "vagrant-omnibus"
require "vagrant-aws"

Vagrant.configure("2") do |config|
  config.omnibus.chef_version = "11.4.0"

  config.vm.box = "dummy"
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV["DEV_AWS_ACCESS_KEY_ID"]
    aws.secret_access_key = ENV["DEV_AWS_SECRET_ACCESS_KEY"]
    aws.keypair_name = ENV["USER"]

    aws.instance_type = "m1.large"
    aws.ami = "ami-2efa9d47" # Ubuntu 12.04 LTS 64-bit instance root store

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/id_rsa"
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path =
      File.expand_path("../../../support/cookbooks", __FILE__)
    chef.add_recipe "chef-inator"
  end
end
